/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as ShareRouteImport } from './routes/share'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as CodegraphRouteImport } from './routes/codegraph'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesIndexRouteImport } from './routes/workspaces.index'
import { Route as WorkspacesIdRouteImport } from './routes/workspaces.$id'
import { Route as AgentsOpenclawRouteImport } from './routes/agents.openclaw'
import { Route as AgentsHermesRouteImport } from './routes/agents.hermes'
import { Route as AgentsClaudeCodeRouteImport } from './routes/agents.claude-code'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const CodegraphRoute = CodegraphRouteImport.update({
  id: '/codegraph',
  path: '/codegraph',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIdRoute = WorkspacesIdRouteImport.update({
  id: '/workspaces/$id',
  path: '/workspaces/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsOpenclawRoute = AgentsOpenclawRouteImport.update({
  id: '/agents/openclaw',
  path: '/agents/openclaw',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsHermesRoute = AgentsHermesRouteImport.update({
  id: '/agents/hermes',
  path: '/agents/hermes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsClaudeCodeRoute = AgentsClaudeCodeRouteImport.update({
  id: '/agents/claude-code',
  path: '/agents/claude-code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/codegraph': typeof CodegraphRoute
  '/memory': typeof MemoryRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/share': typeof ShareRoute
  '/skills': typeof SkillsRoute
  '/agents/claude-code': typeof AgentsClaudeCodeRoute
  '/agents/hermes': typeof AgentsHermesRoute
  '/agents/openclaw': typeof AgentsOpenclawRoute
  '/workspaces/$id': typeof WorkspacesIdRoute
  '/workspaces/': typeof WorkspacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/codegraph': typeof CodegraphRoute
  '/memory': typeof MemoryRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/share': typeof ShareRoute
  '/skills': typeof SkillsRoute
  '/agents/claude-code': typeof AgentsClaudeCodeRoute
  '/agents/hermes': typeof AgentsHermesRoute
  '/agents/openclaw': typeof AgentsOpenclawRoute
  '/workspaces/$id': typeof WorkspacesIdRoute
  '/workspaces': typeof WorkspacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/codegraph': typeof CodegraphRoute
  '/memory': typeof MemoryRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/share': typeof ShareRoute
  '/skills': typeof SkillsRoute
  '/agents/claude-code': typeof AgentsClaudeCodeRoute
  '/agents/hermes': typeof AgentsHermesRoute
  '/agents/openclaw': typeof AgentsOpenclawRoute
  '/workspaces/$id': typeof WorkspacesIdRoute
  '/workspaces/': typeof WorkspacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/codegraph'
    | '/memory'
    | '/settings'
    | '/setup'
    | '/share'
    | '/skills'
    | '/agents/claude-code'
    | '/agents/hermes'
    | '/agents/openclaw'
    | '/workspaces/$id'
    | '/workspaces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/codegraph'
    | '/memory'
    | '/settings'
    | '/setup'
    | '/share'
    | '/skills'
    | '/agents/claude-code'
    | '/agents/hermes'
    | '/agents/openclaw'
    | '/workspaces/$id'
    | '/workspaces'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/codegraph'
    | '/memory'
    | '/settings'
    | '/setup'
    | '/share'
    | '/skills'
    | '/agents/claude-code'
    | '/agents/hermes'
    | '/agents/openclaw'
    | '/workspaces/$id'
    | '/workspaces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  CodegraphRoute: typeof CodegraphRoute
  MemoryRoute: typeof MemoryRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  ShareRoute: typeof ShareRoute
  SkillsRoute: typeof SkillsRoute
  AgentsClaudeCodeRoute: typeof AgentsClaudeCodeRoute
  AgentsHermesRoute: typeof AgentsHermesRoute
  AgentsOpenclawRoute: typeof AgentsOpenclawRoute
  WorkspacesIdRoute: typeof WorkspacesIdRoute
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codegraph': {
      id: '/codegraph'
      path: '/codegraph'
      fullPath: '/codegraph'
      preLoaderRoute: typeof CodegraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$id': {
      id: '/workspaces/$id'
      path: '/workspaces/$id'
      fullPath: '/workspaces/$id'
      preLoaderRoute: typeof WorkspacesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/openclaw': {
      id: '/agents/openclaw'
      path: '/agents/openclaw'
      fullPath: '/agents/openclaw'
      preLoaderRoute: typeof AgentsOpenclawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/hermes': {
      id: '/agents/hermes'
      path: '/agents/hermes'
      fullPath: '/agents/hermes'
      preLoaderRoute: typeof AgentsHermesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/claude-code': {
      id: '/agents/claude-code'
      path: '/agents/claude-code'
      fullPath: '/agents/claude-code'
      preLoaderRoute: typeof AgentsClaudeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  CodegraphRoute: CodegraphRoute,
  MemoryRoute: MemoryRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  ShareRoute: ShareRoute,
  SkillsRoute: SkillsRoute,
  AgentsClaudeCodeRoute: AgentsClaudeCodeRoute,
  AgentsHermesRoute: AgentsHermesRoute,
  AgentsOpenclawRoute: AgentsOpenclawRoute,
  WorkspacesIdRoute: WorkspacesIdRoute,
  WorkspacesIndexRoute: WorkspacesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
